<?php
/**
 * @file
 * Allows setting notices for specific roles
 */
/**
 * Implements hook_permission().
 *
 *  http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 * @return array An array of valid permissions for the module_name module
 */
function rnotices_permission()
{
	return array(
		'administer role notices' => array(
			'title'       => t('Administer Role Notices'),
			'description' => t('Allows the user to set messages for all roles'),
		),
	);
}

/**
 * Implementationation of hook_menu().
 *
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function rnotices_menu()
{
	$items['admin/people/rnotices'] = array(
		'title'            => 'Role Notices',
		'page callback'    => 'drupal_get_form',
		'page arguments'   => array('rnotices_settings'),
		'access arguments' => array('administer role notices'),
		'type'             => MENU_LOCAL_TASK,
	);


	return $items;
}

/**
 * Settings form
 * Admin may enter role notices
 *
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function rnotices_settings($form, &$form_state)
{
	$notices                = variable_get('rnotices_texts', array());
	$roles                  = user_roles(true);
	$form['rnotices_texts'] = array(
		'#tree' => true,
	);
	foreach ($roles as $rid => $role)
	{
		$form['rnotices_texts'][$rid] = array(
			'#type'          => 'textarea',
			'#title'         => t('Notice for @role', array('@role' => $role)),
			'#default_value' => isset($notices[$rid]) ? $notices[$rid] : '',
		);
	}

	// system_settings_form - will default buttons and
	// Drupal will will handle the submiting of the form automatically
	return system_settings_form($form);
}