<?php
/**
 * @file
 * Allows setting notices for specific roles
 */
/**
 * Implements hook_permission().
 *
 *  http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 * @return array An array of valid permissions for the module_name module
 */
function rnotices_permission()
{
	return array(
		'administer role notices' => array(
			'title'       => t('Administer Role Notices'),
			'description' => t('Allows the user to set messages for all roles'),
		),
	);
}

/**
 * Implementationation of hook_menu().
 *
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 */
function rnotices_menu()
{
	$items['admin/people/rnotices'] = array(
		'title'            => 'Role Notices',
		'page callback'    => 'drupal_get_form',
		'page arguments'   => array('rnotices_settings'),
		'access arguments' => array('administer role notices'),
		'type'             => MENU_LOCAL_TASK,
	);


	return $items;
}

/**
 * Settings form
 * Admin may enter role notices
 *
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function rnotices_settings($form, &$form_state)
{
	$notices                = variable_get('rnotices_texts', array());
	$roles                  = user_roles(true);
	$form['rnotices_texts'] = array(
		'#tree' => true,
	);
	foreach ($roles as $rid => $role)
	{
		$form['rnotices_texts'][$rid] = array(
			'#type'          => 'textarea',
			'#title'         => t('Notice for @role', array('@role' => $role)),
			'#default_value' => isset($notices[$rid]) ? $notices[$rid] : '',
		);
	}

	// system_settings_form - will default buttons and
	// Drupal will will handle the submiting of the form automatically
	return system_settings_form($form);
}

/**
 * @return array An array of notices for the current user. keyed by role id(rid)
 */
function _rnotices_get_notices()
{
	global $user; // user viewing page at the time
	$all_notices  = variable_get('rnotices_texts', array());
	$user_notices = array_intersect_key($all_notices, $user->roles);
	foreach ($user_notices as &$notice)
	{
		$notice = check_plain($notice);
	}

	return $user_notices;
}

/**
 * Implements hook_block_info().
 *
 * Allows the module to define blocks
 *
 * @return array Block keyed by delta strings
 */
function rnotices_block_info()
{
	$blocks['rnotices_mine'] = array(
		'info' => t('Role Notices'),
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook is called to display a block
 *
 * @param string $delta
 *   key to determine which block should be displayed
 *
 * @return array
 */
function rnotices_block_view($delta = '') // Delta is the block being viewed, tested in switch
{
	switch ($delta)
	{
		case 'rnotices_mine':
			$notices = _rnotices_get_notices();
			//use "theme" function get rendered HTML list -- themes can override this
			//***also I don't put in HTML in the module
			$themed_notice_list = theme('item_list', array('items' => $notices));

			return array(
				'subject' => t('Notices'),
				'content' => $themed_notice_list,
			);
			break;
	}
}