<?php
/**
 * @file
 * Allows setting notices for specific roles
 * version 7.demo.2
 */
/**
 * Implements hook_permission().
 *
 *  http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_permission/7
 * @return array An array of valid permissions for the module_name module
 */
function rnotices_permission() {
  return array(
    'administer role notices' => array(
      'title' => t('Administer Role Notices'),
      'description' => t('Allows the user to set messages for all roles'),
    ),
  );
}

/**
 * Implementationation of hook_menu().
 *
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 * ***You have to clear the menu cache after you make changes to this function
 */
function rnotices_menu() {
  $items['admin/people/rnotices'] = array(
    'title' => 'Role Notices',
    'page callback' => 'rnotices_settings_page',
    'access arguments' => array('administer role notices'),
    'type' => MENU_LOCAL_TASK,
  );


  return $items;
}

/*
 * Page Callback for Settings form
*/
function rnotices_settings_page() {
  // @see http://api.drupal.org/api/drupal/includes%21form.inc/function/drupal_get_form/7
  $form = drupal_get_form('rnotices_settings');
  return $form;
}

/**
 * A very simple form.
 * This function will be called by drupal_get_form
 * We will never call it directly
 *
 * @param array $form
 * @param array $form_state
 * @return array
 */
function rnotices_settings($form, &$form_state) {
  $text = variable_get('rnotices_texts', '');
  $form['rnotices_texts'] = array(
    '#type' => 'textarea',
    '#title' => t('Notice for ALL roles'),
    '#default_value' => $text,
    '#description' => t('Enter the text here!'),
  );


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save Notices',
  );

  return $form;
}

function rnotices_settings_submit($form, &$form_state) {
  $text = $form_state['values']['rnotices_texts'];
  variable_set('rnotices_texts', $text);
}